/**
 * Fake-git PATH shadow — freezes the git status/log/user-name fields Claude Code
 * reads at session start so `--resume` doesn't invalidate the prompt cache when
 * the real repo state (uncommitted changes, new commits) has drifted since the
 * session began. Branch is intentionally left untouched: Claude Code reads
 * .git/HEAD directly (not via `git`), so it can't be shadowed this way, and
 * mutating the real HEAD file is out of scope (shared repo state, too risky).
 *
 * A SessionStart hook (~/.claude/hooks/) injects the real git info into
 * context separately and drops an `.unlocked` marker in the shadow dir once
 * it has run, after which this wrapper passes every command through to the
 * real `git` — so mid-session Bash tool calls always see live data.
 *
 * PATH is process-wide, so this wrapper also intercepts `git` calls made by
 * unrelated hooks against unrelated repos (e.g. a hook that checks a config
 * dir's own git status). It only freezes commands targeting the repo
 * claude-nonstop actually spawned for — anything else always gets the real
 * git, lock state notwithstanding.
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const DIR_PREFIX = 'claude-nonstop-fake-git-';
const SWEEP_GRACE_MS = 5 * 60 * 1000; // don't touch dirs younger than this — may be mid-setup

function wrapperScript(realGitPath, targetToplevel) {
  return `#!/bin/bash
# Generated by claude-nonstop (lib/fake-git.js) — do not edit, regenerated per session.
DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REAL_GIT="${realGitPath}"
TARGET_TOPLEVEL="${targetToplevel}"

if [ -f "$DIR/.unlocked" ]; then
  exec "$REAL_GIT" "$@"
fi

if [ -z "$TARGET_TOPLEVEL" ]; then
  exec "$REAL_GIT" "$@"
fi

# Only freeze commands targeting the repo we were spawned for — a \`-C <path>\`
# argument or the caller's cwd may point somewhere else entirely (e.g.
# another hook checking an unrelated repo), which always gets the real git.
observed_cwd="$PWD"
prev_flag=""
for arg in "$@"; do
  if [ "$prev_flag" = "-C" ]; then
    observed_cwd="$arg"
    break
  fi
  prev_flag="$arg"
done

observed_toplevel="$("$REAL_GIT" -C "$observed_cwd" rev-parse --show-toplevel 2>/dev/null)"
if [ "$observed_toplevel" != "$TARGET_TOPLEVEL" ]; then
  exec "$REAL_GIT" "$@"
fi

args="$*"
case "$args" in
  *"status --short"*|*"status --porcelain"*)
    echo ""
    exit 0
    ;;
  *"log --oneline"*)
    echo ""
    exit 0
    ;;
  *"config user.name"*)
    echo ""
    exit 0
    ;;
  *)
    exec "$REAL_GIT" "$@"
    ;;
esac
`;
}

/**
 * Create a per-spawn shadow directory containing a fake `git` on PATH.
 * Must be called before spawning claude so the dir can be prepended to PATH.
 */
export function createFakeGitDir(targetCwd) {
  const realGitPath = execFileSync('which', ['git'], { encoding: 'utf8' }).trim();

  let targetToplevel = '';
  try {
    targetToplevel = execFileSync(realGitPath, ['-C', targetCwd, 'rev-parse', '--show-toplevel'], {
      encoding: 'utf8',
    }).trim();
  } catch {
    // Not a git repo — leave empty, wrapper will always pass through.
  }

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), DIR_PREFIX));
  fs.writeFileSync(path.join(dir, 'git'), wrapperScript(realGitPath, targetToplevel), { mode: 0o755 });
  return { dir, realGitPath };
}

/** Record the spawned child's pid so a later sweep can tell if it's still alive. */
export function finalizeFakeGitDir(dir, pid) {
  try {
    fs.writeFileSync(path.join(dir, '.pid'), String(pid));
  } catch {}
}

/** Remove a shadow dir. Best-effort — never throws. */
export function cleanupFakeGitDir(dir) {
  try {
    fs.rmSync(dir, { recursive: true, force: true });
  } catch {}
}

function isPidAlive(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch (err) {
    return err.code !== 'ESRCH';
  }
}

/**
 * Remove shadow dirs left behind by processes that died before they could
 * clean up after themselves (SIGKILL, crash, power loss — nothing catchable
 * runs in those cases, so this sweep is the only recovery path).
 */
export function sweepStaleFakeGitDirs() {
  const base = os.tmpdir();
  let entries;
  try {
    entries = fs.readdirSync(base);
  } catch {
    return;
  }

  for (const name of entries) {
    if (!name.startsWith(DIR_PREFIX)) continue;
    const dir = path.join(base, name);

    try {
      const stat = fs.statSync(dir);
      if (Date.now() - stat.birthtimeMs < SWEEP_GRACE_MS) continue;

      const pidPath = path.join(dir, '.pid');
      let stale = true;
      if (fs.existsSync(pidPath)) {
        const pid = Number(fs.readFileSync(pidPath, 'utf8').trim());
        stale = !Number.isFinite(pid) || !isPidAlive(pid);
      }

      if (stale) cleanupFakeGitDir(dir);
    } catch {}
  }
}
